### ISSUE TITLE
Holographic Scoreboards and SimpleClans

### ISSUE THREAD

**Issue by Peter234679** [rlf/Holographic-Scoreboard#16]
I'm trying to create a scoreboard with the command /hgs create stats 10s player clan leaderboard but after it's created it just says "unable to execute command clan leaderboard" any suggestions? I am using version 1.3.8 of Holographic Scoreboards

**Comment by rlf** [comment]
the `player` mode is a really hacky solution, and should only be used when no `console` options exist.

When HGS tries to execute a `player` command, it tries to find the player closest to the scoreboard, and executes it on his behalf - that means, any commands using the `player`, needs to be accessible for all players on the server.

**Comment by Peter234679** [comment]
Still all players on my server at least have the correct permissions to run the command and even when i'm the only player on the server and op'ed, it still says that the command could not be executed.

**Comment by Peter234679** [comment]
Any suggestions?

**Comment by rlf** [comment]
As I recall it, the SimpleClans doesn't use "the normal" way of interacting with the user.
That means, I have no reliable way of getting the output from (let alone executing) the command.

I suggest you file a feature request with simple clans, providing access to the "scoreboard-commands" from console.
