### ISSUE TITLE
Not working properly on Spigot 1.8.3

### ISSUE THREAD

**Issue by Projekt4769** [rlf/Holographic-Scoreboard#17]
Plugin seems to run command as a player/console and display the answer in respective chat, not as a scoreboard. It doesn't create a scoreboard at all, although I have HologramDisplays installed.

![](http://i.gyazo.com/81383cbd02c6fba2c3ce469e9d2345fd.png)

![](http://i.gyazo.com/990caa62ea7cb0f5669cbf4122195efd.png)

**Comment by rlf** [comment]
Please provide the command (and version of the plugin) you are trying to get hgs to execute.

**Comment by Lahemees47** [comment]
Command was "/money top" from Craftconomy3, but other commands acted the same aswell.
Holographic Scoreboard v1.3.8 by R4zorax.

**Comment by rlf** [comment]
It works on my server, running "the latest Spigot 1.8.3" build.

Could you provide the server-log, in pastebin, might help me resolve the issue.
