### ISSUE TITLE
unable to execute <world> command

### ISSUE THREAD

**Issue by AvatarAcid** [rlf/Holographic-Scoreboard#21]
I can't seem to get HGS working which is a shame.

Every command, console or player, I run returns unable to execute.

java 1.8.0_45
Spigot 1.8.8
holographicdisplays: 2.1.10
holographichscoreboard: 1.3.9
ProtocolLib: 3.6.4

I've tried various plugins/commands
craftconomy3: money top
mywarp: warp list
bounty: bounties

All of these run on console but still no luck in HGS, could you assist?

**Comment by rlf** [comment]
Do you use the colon? If yes, try without.

**Comment by AvatarAcid** [comment]
I should have put the command I used, apologies :)

I did not put a : ? I did not use the command backslash if that is what you meant?

Here is my board:

boards:
  mint_board:
    command: the_burrows money top
    interval: 10m
    sender: console
    delay: 5s
    location:
      world: the_burrows
      x: 97.3585128929917
      y: 49.62
      z: -42.69999998807907

**Comment by rlf** [comment]
Don't prepend the command with the world name.

**Comment by AvatarAcid** [comment]
I have tried without, same effect. That was my fifth or sixth try, last option was to try world name.

**Comment by rlf** [comment]
Sorry, I don't know of any <world> command?
What is that? and when is it released? and how does it work?
I would assume you had to do `money top` and not `the_burrows money top`.

**Comment by AvatarAcid** [comment]
I have attempted both money top and the_burrows money top.  the_burrows is world.

Ok, so I think the issue is mine, maybe?  Your plugin outputs to chat if I use "player" and to server console if I use "console" - but, isn't it suppose to create a hologram to output to??  Like Holographic Displays holograms itself?

**Comment by AvatarAcid** [comment]
So when I do this:
[01:11:33 INFO]: AvatarAcid issued server command: /hgs create test6 5m player money top

I get the command sent to me in form of chat, as I had typed it msyelf. How do I put it in a hologram?

**Comment by rlf** [comment]
If at all possible, please use the `console`, as the `player` is very buggy, and is only included to handle places where there is no other way.

It shouldn't sent it to you, but tbh. I haven't tested the player part for ages.

**Comment by AvatarAcid** [comment]
Well maybe I need to make you a video. When I select console, it doesn't create a hologram and it just sends the command output to the console.

**Comment by AvatarAcid** [comment]
Hello rlf.

I had a second go at this, some things are working. I deleted the jar and config files and started over. I tested firstly with mcMMO as you had that as an example. It works. I then tested with Bounties, it too works. However I then tested with CraftConomy3's money top command and it does not work.

The only thing that happens is that the command gets sent to and printed at the console, it does not make it into the hologram. Here is a screen shot example of the Bounties hologram that is working and the console output after a /hgs reload - showing you the issue. Can you advise?

https://copy.com/qmry8rGUWfQlirmB

**Comment by rlf** [comment]
If it's simply a matter of the plugin not returning the text fast enough (i.e. some is getting into the scoreboard, some is not), then you can tweak how long time HGS waits for output from a command, by increasing the delay.

```
/hgs edit craftop delay 30s
```
will set the delay to 30s (meaning, the scoreboard will execute the command on refresh, and then wait 30s for the command to complete, and then display all output gathered in that time-period in the scoreboard).

The default delay is 5s - so perhaps a value of 10s-15s will be sufficient.

Remember to save your changes once happy `/hgs save`.

**Comment by AvatarAcid** [comment]
Thanks for your reply rlf. I do think that it is the case, CraftConomy isn't communicating through normal means. I hit enter on the reload command and it pops into the console instantly, less than 500ms response time on that and long before the other HGS bounties 5s refresh.

This looks to be CraftConomy's issue.

**Comment by rlf** [comment]
Yes, did some digging, no way HGS can support CraftConomy3 without making specific code for it (and even then, it will be hard).

See https://github.com/greatman/GreatmancodeTools/blob/master/src/main/java/com/greatmancode/tools/caller/bukkit/BukkitPlayerCaller.java

**Comment by AvatarAcid** [comment]
Alright well thanks for taking the time to do this with me! I've already made a request for a smaller newer plugin here:
http://dev.bukkit.org/bukkit-plugins/multi-world-money/tickets/34-add-world-balance-top-list-command/

I will try to get my server's money standings up somehow :)  

Take care, love the plugin!
