### ISSUE TITLE
Holograms showing only 1 line of command

### ISSUE THREAD

**Issue by Foreme** [rlf/Holographic-Scoreboard#23]
I have 2 holographic scoreboards set up in my Survival spawn, one displays mctop rankings and the other displays baltop rankings, occasionally one of the two will randomly display only 1 line of the command, it normally fixes itself when it is next refreshed.

Also, very strange thing. In my console it shows the command /baltop being run twice
[02:10:36 INFO]: CONSOLE issued server command: /baltop 
[02:10:36 INFO]: CONSOLE issued server command: /baltop 

But I only have 1 baltop scoreboard and 1 mctop scoreboard, the mctop command is never run but the scoreboard works.

Here is my config:

boards:
  baltop:
    command: baltop
    interval: 5m
    sender: console
    delay: 5s
    location:
      world: world
      x: 86.50135844342971
      y: 145.62
      z: 264.5177913305476
  powerlevel:
    command: mctop
    interval: 5m
    sender: console
    delay: 5s
    location:
      world: world
      x: 100.98139918707793
      y: 145.62
      z: 270.8895685566571

**Comment by rlf** [comment]
That is because the baltop only shows one line, when refreshing.
You can set the delay higher if you want it to get it right.
The "double baltop" is known, but not sure how to fix it.

**Comment by Foreme** [comment]
Thank you
